### ISSUE TITLE
Serve not working

### ISSUE THREAD

**Issue by itwasmattgregg** [JimSchofield/blogli#3]
Getting this error when trying to use blogli-serve from the example project:

```
+-----------------------+
| Serving blogli output |
+-----------------------+

Serving from: ./output/
/bin/sh: http-server: command not found
```

Do I need to have any other node_modules installed?

And watch doesn't show any errors but it dies after the "serving" header

**Comment by JimSchofield** [comment]
TODO: Need to execute `npm run http-server` instead of calling a global install that probably isn't installed already

**Comment by JimSchofield** [comment]
In 0.1.3 we're now calling `http-server` using `npx`.  I don't think this is the most attractive or correct way to do it, but it works for now.  Later I would like to investigate creating a simple express server to handle serving possibly?
